on:
  [push]
jobs:
  nuke:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old GitHub docker images
        uses: CirrusMD/github-action-clean-docker-packages@v2.0.0
        with:
          gh-token: ${{ secrets.GH_TOKEN_DOCKER_CLEAN }}
          package-name: fun-with-containers
          dry-run: false
          num-keep: 10
